services:
  - type: web
    name: superset-web
    env: docker
    plan: starter
    branch: main
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SUPERSET_SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: host-insights-db
          property: connectionString

databases:
  - name: host-insights-db
    plan: free
    postgresMajorVersion: 14
